### ISSUE TITLE
Efficiency Improvements

### ISSUE THREAD

**Issue by shadoxxhd** [Col-E/Recaf#116] opened 2019-02-22 17:25 UTC
## C&P Support

Allow users to copy/paste methods/variables/sections of bytecode.

**Extra details**:

* Ideally convert the specific resource to text and put in in the OS clipboard - this allows sharing via pastebin as well as cross-process C&P.
* Most important for instructions and methods, as variables are quicker to add and classes can be duplicated with winrar.
***
## Keyboard Instruction Input

Either allow the insertion of new instructions via shortcuts, or, even better, allow us to write instructions as text which is then parsed to bytecode (for bonus points, add autocomplete for instruction and class/variable names).

**Extra details**:

* Obviously the smarter the suggestion the system can provide, the better, but simple syntax checking with suggestions of instruction names and jar/project-local class/field names would already be quite efficient. Add previously used non-local class names to the list, and it's close to perfect.
* Requires some additional UI, but speeds up work flow considerably (writing instructions w/ autocomplete might be more than ten times as fast as selecting them via UI).
***

## Recompile Feature

This might take a lot of work, but it would be nice if users could just modify the java code in the decompile window and let the application do the conversion to bytecode. I personally like the freedom direct instruction editing gives, but for most users this addition would make Recaf a much more powerful tool.

**Extra details**:

* If the library used for decompiling can already reverse this process, integration should be quite simple.
* Ideally the bytecode should change as little as possible when making small tweaks, though this is of low importance.

***
## Minor Enhancements

**Simple**:
* Remember the last path used for opening/saving files.
* Add recent files/folders list to file menu.
* Ask before quitting if changes occured since last save.
* Doubleclick on a class/method should open its definition in a new window (decompile and bytecode view).
* Rightclick on a class/method should give option to open definition/search for uses/refactor(rename everywhere) (decompile and bytecode view).
* Add window that lists (other) open windows.
**Advanced**:
* Allow multicursor selection for editing instrutions
* Add regex search/replace with functional conditions (ie. class name that starts with "wi", data type name "int" (useful eg. if you don't want to want to change the class name Mint to Mlong, but all ints to longs)
* Structure Detection: Allow semiautomatic application of simple structure rules (automate repetetive tasks; eg. if you want to add several class entries to an array, the constructor code for them could be automatically generated when C&P duplicating the last 3 entries (should be optional/configurable)
* Allow using tabs instead of new windows?

For C# there is a program called DNSpy, which allows you to edit C# bytecode extremely efficiently. If you are looking for further enhancements/extensions for Recaf, it is probably the best example to compare yourself to.

**Comment by Col-E** [comment] 2019-02-22 22:49
**C&P Support**

* :+1: will do
* What do you mean by: `* Most important for instructions and methods, as variables are quicker to add` ? I get the first point, not this one though.

**Keyboard Instruction Input**

* How would such a shortcut work? 
* The text representation is arbitrary, but I could probably make a parser for `Text -> Bytecode`
* :+1: 

**Recompile Feature**

* This already is supported, so long as the [compiler classes are on the classpath](https://github.com/Col-E/Recaf/blob/master/src/me/coley/recaf/util/Misc.java#L22). Running Recaf with a JDK's `bin/java` should resolve this. 
* I don't control the decompiler or the compiler, so I can't enforce keeping most of the bytecode the same. 
    * There could be some workarounds though:
        * Use the java-parser API to figure out which method(s) have been modified, compile the code, and replace only the methods with the newly compiled code's bytecode. Leaving other methods and such in-tact
        * Re-add recompilation from single-method decompile. I removed this due to some complexities in this process not being easily resolvable.

**Minor**

If there's no comments on a suggestion, assume :+1: 

* `Doubleclick on a class/method should open its definition in a new window`
    * So, on the tree navigation panels? 
* `Rightclick on a class/method should give option to open definition/search for uses/refactor`
    * Again, on the tree navigation panels?
    * :+1: for `open def/search` but not `refactor` due to how that's handled. That'll be reserved for the definition window
* `Allow multicursor selection for editing instrutions`
    * Is this any different than `Control` + `M1`?
* `Add regex search/replace with functional conditions`
    * I'd like more specifics. What kind of data will this allow to be replaced? Is it anything like [this example plugin](https://github.com/Col-E/Recaf-plugin-workspace/releases/tag/example-str-replace)?
* `Structure Detection`
    * Can you mock up a concrete example? Like the action you want to do and the bytecode that would be auto-generated?
* `Allow using tabs instead of new windows?`
    * Not sure how I feel about this one. I do agree too many windows gets cluttered, but I don't know where the tabs would be placed and how to keep track of them _(What windows are open suggestion)_

**Comment by andylizi** [comment] 2019-02-23 05:30
> The text representation is arbitrary, but I could probably make a parser for `Text -> Bytecode`

Maybe you're looking for [Jasmin](https://github.com/jasmin) or its successor [Krakatau](https://github.com/Storyyeller/Krakatau):
```jasmin
.class public HelloWorld
.super java/lang/Object

.method public <init>()V
    aload_0
    invokenonvirtual java/lang/Object/<init>()V
    return
.end method

.method public static main([Ljava/lang/String;)V
    .limit stack 2
    getstatic java/lang/System/out Ljava/io/PrintStream;
    ldc "Hello World!"
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    return
.end method
```
[JBE](https://set.ee/jbe/) also has a similar feature:
![jbe](https://user-images.githubusercontent.com/12008103/53282095-fa312b00-376d-11e9-8f81-3b3e065fe7bf.png)

**Comment by shadoxxhd** [comment] 2019-02-23 18:50
**C&P**
Copying methods and instructions is something I really wanted multiple times, while manually copying classes or fields was already doable.

**Keyboard Input**
I was imagining a shortcut for 'insert instruction, and then a mapping of keyboard input to instructions - either a search field for instruction name where you can comfirm your selection with enter, or some menu tree.
The jasmin code representation might be a bit more work, but would be much more convenient and extremely appreciated.

**Recompile**
How do you access this? Just like someone suggested there to be an apply/discard dialog when closing the instruction editor, there should be a explicit 'recompile edited source code' button. Changes should certainly not be applied automatically, especially if there is no undo button. If you are trying to search in the decompiled code, sometimes the first few characters of the search term are written in the code window instead of the search bar (it opens with a large delay (~0.2s)) - if the code is recompiled automatically, this could lead to disaster.

**Minor**

> Doubleclick on a class/method should open its definition in a new window
>> So, on the tree navigation panels?

I meant in the instruction or code editor (only when using text-based instruction editor, of course - in the module-based instruction editor a right-click option is better).

>Allow multicursor selection for editing instrutions
>>Is this any different than Control + M1?

In the current modular instruction view not really, though you can't do much with what you have selected. A full multi-cursor support would allow editing multiple names/instructions at the same time - something which doesn't work with Ctrl+M1 selection (Sublime Text 3 implements this, and I use the feature quite often).

>Add regex search/replace with functional conditions
>>I'd like more specifics. What kind of data will this allow to be replaced? Is it anything like this example plugin?

Pretty much, though my suggestion is including functional symbols in the regex system: eg. being able to only replace some string in class names, not in method/field names (or the opposite), and select the files/folders it replaces it in. It also makes it possible to efficiently search for eg. a specific method with nothing but text input (I prefer using my keyboard over using my mouse for things like this :P)

>Structure Detection
>>Can you mock up a concrete example? Like the action you want to do and the bytecode that would be auto-generated?

Java code (from minecraft mod "ebwizardry"):
```
static {
        MAGIC = new Element(new Style().func_150238_a(TextFormatting.GRAY), "simple", "ebwizardry");
        POWER = new Element(new Style().func_150238_a(TextFormatting.LIGHT_PURPLE), "power", "ebwizardry");
        FIRE = new Element(new Style().func_150238_a(TextFormatting.DARK_RED), "fire", "ebwizardry");
        ICE = new Element(new Style().func_150238_a(TextFormatting.AQUA), "ice", "ebwizardry");
        LIGHTNING = new Element(new Style().func_150238_a(TextFormatting.DARK_AQUA), "lightning", "ebwizardry");
        NECROMANCY = new Element(new Style().func_150238_a(TextFormatting.DARK_PURPLE), "necromancy", "ebwizardry");
        EARTH = new Element(new Style().func_150238_a(TextFormatting.DARK_GREEN), "earth", "ebwizardry");
        SORCERY = new Element(new Style().func_150238_a(TextFormatting.GREEN), "sorcery", "ebwizardry");
        HEALING = new Element(new Style().func_150238_a(TextFormatting.YELLOW), "healing", "ebwizardry");
$VALUES = new Element[]{MAGIC, FIRE, ICE, LIGHTNING, NECROMANCY, EARTH, SORCERY, HEALING, POWER};
    }
```
If I wanted to add let's say 2 new entries, I would have to copy [this](https://imgur.com/ZWVB4Sb) bytecode by hand both times, in addition to handling the insertion and expansion of the array. C&P helps a lot, so this has a very low priority, but what I imagined was that I could somehow signal my intent to expand this array, and the expansion and generation of copied example constructors would be done automatically, resulting in the following:
```
...
HEALING = new Element(new Style().func_150238_a(TextFormatting.YELLOW), "healing", "ebwizardry");
HEALING = new Element(new Style().func_150238_a(TextFormatting.YELLOW), "healing", "ebwizardry");
$VALUES = new Element[]{MAGIC, FIRE, ICE, LIGHTNING, NECROMANCY, EARTH, SORCERY, HEALING, POWER, HEALING, HEALING};
```
(in java code view)


Tabs could be arranged similarly to DNSpy, but with a window list window the chaos of huge 'window swarms' could already be handled pretty well I guess.

@andylizi [Jasmin](http://jasmin.sourceforge.net/instructions.html) is exactly what I meant when I was talking about a bytecode <=> text mapping.

Maybe [this](https://web.archive.org/web/20180430195817/http://cs.au.dk/~mis/dOvs/jvmspec/ref-Java.html) could be included as a help function, since it is no longer available online (apart from archive.org)?

**Comment by Col-E** [comment] 2019-02-24 20:47
> **C&P**
Copying methods and instructions is something I really wanted multiple times, while manually copying classes or fields was already doable.

Copying instructions is already possible

* Select multiple instructions -> right click -> save as block
* Right click -> insert block

> **Keyboard Input**
I was imagining a shortcut for 'insert instruction, and then a mapping of keyboard input to instructions - either a search field for instruction name where you can comfirm your selection with enter, or some menu tree.

Oh, so a keyboard shortcut would pop up a search bar, you type in the opcode what you want to insert, then pressing enter will bring up the opcode window with your specified opcode for further clarification _(until text->code is supported)_?

> **Recompile**
How do you access this? Just like someone suggested there to be an apply/discard dialog when closing the instruction editor, there should be a explicit 'recompile edited source code' button. Changes should certainly not be applied automatically

Access by right click -> Recompile.

Also, its not automatic. Since its relevant, I'll include a note on how the UI works below.

> **Text -> Bytecode**
The jasmin code representation might be a bit more work, but would be much more convenient and extremely appreciated.

Yeah, that would be a nice thing to have. I'll make sure to add some support for this in the future.

> A full multi-cursor support would allow editing multiple names/instructions at the same time

I don't think with how the UI works right now that this will be possible to implement. 

> My suggestion is including functional symbols in the regex system: eg. being able to only replace some string in class names, not in method/field names (or the opposite), and select the files/folders it replaces it in. It also makes it possible to efficiently search for eg. a specific method with nothing but text input

Ok so custom identifiers in regex, that does sound useful but I'm not sure how I would approach that. Working with regex is easy, extending it would be something new to me.

This does line up with what I want to do with the search function anyways. At one point I wrote down this note:

> * Rewrite search to allow for custom search algorithms given the same `Input`
>     * Allow users to query by writing raw JSON requests _(UI exports to JSON)_ or some similar system
>     * Allow for union / disjoint for multiple search elements

There is a LOT I want to do here, but the issue is free time & not breaking everything with constant rewrites.

> C&P helps a lot, so this has a very low priority, but what I imagined was that I could somehow signal my intent to expand this array, and the expansion and generation of copied example constructors would be done automatically

Guessing intent is not a simple task. It certainly would be cool, but I don't think I'll be adding something this complex any time soon.

> Tabs could be arranged similarly to DNSpy, but with a window list window the chaos of huge 'window swarms' could already be handled pretty well I guess.

:+1: 

> [Jasmin](http://jasmin.sourceforge.net/instructions.html) is exactly what I meant when I was talking about a bytecode <=> text mapping.
>
> Maybe [this](https://web.archive.org/web/20180430195817/http://cs.au.dk/~mis/dOvs/jvmspec/ref-Java.html) could be included as a help function, since it is no longer available online (apart from archive.org)?

Its a bit outdated and IIRC some articles are missing information. Great resource otherwise :+1: 

Also didn't know it was 404ing. I'll have to update my link for the standard opcode to something else.

As for inclusion of help, I'd probably make an equivalent for it and put it in the online docs like [this article on Objectweb ASM's opcodes](https://col-e.github.io/Recaf/opcodes.html)

***

**How the UI works in general**

Right now most of the windows in Recaf are mostly auto-generated. I use [ControlfFX's PropertySheet](http://fxexperience.com/controlsfx/features/#attachment_3064) control. The way it works is that it behaves as a visual wrapper of some data structure. Each field of the structure is represented by a labeled control. When the state of a control changes, the field they represent is changed immediately. Since PropertySheet does some basic type validation, this doesn't cause any problems. For example if I'm editing a field `List<String> names` and I want to change it to a set I will have to temporary make `desc` an invalid value while I type out `Set`. But the last update the control receives is  correct, so it doesn't matter what has happened before.

> Just like someone suggested there to be an apply/discard dialog when closing the instruction editor ...

I personally am not a fan of having to hit a confirm button dozens of times so I thought the PropertySheet approach was valid.

**Comment by shadoxxhd** [comment] 2019-02-24 21:54
Blocks are helpful, but not really convenient to use (especially since I have no clue how I can remove blocks I no longer need).

The keyboard shortcut stuff would be nice while you work on a jasmin parser, but I don't know if it is worth the work for something that will hopefully be changed to something else anyway (or do you want to keep the 'instruction module' based editoras an option?).

The recompile feature is something I wasn't aware of at all when first posting this, and I haven't yet tried to use it in an actual project. Some hint for new users would probably help here.

Apply/discard should be optional, but would be quite helpful depending on what you work on. When modifying large projects, you sometimes make changes you didn't intent, and can't easily reconstruct the old code. Having a 'discard changes' option can save hours of work in cases like that (yes I know, saving more often reduces that risk). Applying automatically when you close the window might be a little bit quicker, but I'd personally prefer the safety of always having a way back before comitting to the changes.

**Comment by Col-E** [comment] 2019-02-24 22:30
> Blocks are helpful, but not really convenient to use (especially since I have no clue how I can remove blocks I no longer need).

:eyes: I admit there's no way to delete them via the UI right now... But you can remove them in the `rc_blocks.json` I'll have to fix that.

> (or do you want to keep the 'instruction module' based editoras an option?) 

I'll probably have an option to do one or the other in the UI config. 

> The recompile feature is something _I wasn't aware of at all_ when first posting this, and I haven't yet tried to use it in an actual project. Some hint for new users would probably help here.

I think it would be beneficial for there to be a _Welcome_ screen / tutorial for first-time users that would display tips / tricks / feature example uses. 

> Apply/discard should be optional, but would be quite helpful depending on what you work on.

True, but thats very low on the priority list for me. Maybe some time down the road. I do believe text-fields support `Control + Z` by default in the meantime.

**Comment by shadoxxhd** [comment] 2019-03-01 13:58
>True, but thats very low on the priority list for me. Maybe some time down the road. I do believe text-fields support `Control + Z` by default in the meantime.

If the implementation is the problem, you could simply let the UI element edit a copy of the original data structure, and when closing the window check whether anything was changed.

**Comment by Col-E** [comment] 2019-03-09 08:28
Working on copy/paste: https://github.com/Col-E/Recaf/blob/master/src/me/coley/recaf/ui/component/editor/InsnListEditor.java#L202

1. Select some opcodes
2. `Control + C`
3. Select the opcode you want to paste before
4. `Control + V`
5. Copied code placed before the selection

**Comment by shadoxxhd** [comment] 2019-03-09 13:57
Why paste before the selected instruction and not after? Not a big deal, but paste after would feel more natural to me.

**Comment by Col-E** [comment] 2019-03-09 19:58
Didn't think about it, I can change that or make it a config option.

**Comment by Col-E** [comment] 2019-03-10 23:42
Changed the order so that pasting puts items AFTER the selection

**Comment by Col-E** [comment] 2019-04-12 05:13
In 63e9d45f5427dddcf91c6f73edc53593a7b4a586 

* Added `File -> Recent` menu.
* File selection for open/export is now persistent in the config _(Yet hidden from the config UI)_

**Comment by Col-E** [comment] 2019-04-23 06:20
> # Keyboard Instruction Input

Started working on an assembler. Along with this, I will be slightly changing the way instructions are displayed in the method instructions window so that they are more consistent with one another. The syntax shown in the instructions window will not perfectly mirror that of the assembler so that it can show more verbose informaiton _(as it currently does)_. The assembler will be simple, more details coming later on that though.

Here is a markup of:
* What opcodes look like now
* What I want opcodes to look like later _(Marked with `Alternative`, following an ASM instruction type)_
* How the assembler will pattern match input 

```
LdcInsnNode             LDC "Hello World" 
LdcInsnNode             LDC 1
Alternative:            LDC 1f
Alternative:            LDC 1d
Alternative:            LDC 1l
Alternative:            LDC 1j
                        <OPCODE> <VALUE>

InsnNode                ICONST_0                      
InsnNode                NOP         
                        <OPCODE>

IntInsnNode             BIPUSH 100
                        <OPCODE> <VALUE>

VarInsnNode             ALOAD 0          
Alternative:            ALOAD this
                        <OPCODE> <VARIABLE>
                        - Allow names as variables

IincInsnNode            IINC (1)++        
IincInsnNode            IINC (1)--        
IincInsnNode            IINC (1) += 2     
IincInsnNode            IINC (1) += -2 
Alternative:            IINC $1 + 1
Alternative:            IINC $2 - 1
                        <OPCODE> <VARIABLE> <OPERATION> <VALUE>
Alternative:            IINC $1 +1
Alternative:            IINC $1  1
Alternative:            IINC $2 -1
                        <OPCODE> <VARIABLE> <VALUE>
                        - Allow names as variables?

FieldInsnNode           GETSTATIC System.out PrintStream
                        <OPCODE> <HOST>.<NAME> <TYPE>

MethodInsnNode          INVOKEVIRTUAL PrintStream.print(Object)void
                        <OPCODE> <HOST>.<NAME>(<ARG-TYPE>...)<RETURN-TYPE>

JumpInsnNode            IFEQ       [$0 == 0  -> offset] (13: LABEL A)
Alternative:            IFEQ       13: LABEL A ($0 == 0  -> offset)  
Alternative:            IFEQ 13
Alternative:            IFEQ LABEL A
Alternative:            IFEQ A
                        <OPCODE> <OFFSET/LABEL-ID>


TableSwitchInsnNode     TABLESWITCH  range[0-2] offsets[22, 24, 26] dflt[28]
Alternative:            TABLESWITCH  range[0-2] offsets[A, B, C]    dflt[D]
                        <OPCODE> range[<RANGE>] offsets[<OFFSET/LABEL>...] dflt[<OFFSET/LABEL>]

LookupSwitchInsnNode    LOOKUPSWITCH  [0->22, 1->24] dflt[26]
Alternative:            LOOKUPSWITCH  [0->A, 1->B]   dflt[C]
                        <OPCODE> [<MAPPING>...] dflt[<OFFSET/LABEL>]

LabelNode               LABEL A           
                        ... <LABEL> 

LineNumberNode          LINE 10 (13: LABEL A)
Alternative:            LINE 10:13
Alternative:            LINE 10:LABEL A
Alternative:            LINE 10:A
                        <LABEL>:<LINE>


MultiANewArrayInsnNode  MULTIANEWARRAY Object x3
Alternative:            MULTIANEWARRAY Object[][][]
                        <OPCODE> <TYPE><LEVEL>

TypeInsnNode            NEW String
                        <OPCODE> <TYPE>
```

**Comment by Col-E** [comment] 2019-05-07 03:48
As of 930a0191f82d179861027c5ee2f44a39995df17f the assembler is mostly done. All that needs to be done is to add some extra functionality to the UI. I'm thinking something like this for the assembler window:

![image](https://user-images.githubusercontent.com/21371686/57270461-5d3a1a80-7059-11e9-9c1c-0c13485c590c.png)

Not final, but a general idea.

**Comment by shadoxxhd** [comment] 2019-05-07 04:01
Would a simple autocomplete functionality be out of scope?
For example, completing "new String\n" to "new java/lang/String" (if previously used, and no other String class known in current context - if multiple classes with the same name are used in a single project, a list should pop up), and opening a list when typing "farto" containing "package/fartoolongtypename" and "fartoo/long/typename" (along with other possible matches).
List sorting according to local relevance and personal usage would add a bit more conveniance, but might take more work to implement than it is worth.

**Comment by Col-E** [comment] 2019-05-07 04:20
> Would a simple autocomplete functionality be out of scope?

I plan on adding this. It'll require some significant changes to what I've pushed, but its well worth the effort.

> List sorting according to local relevance and personal usage would add a bit more conveniance, but might take more work to implement than it is worth.

I'd love to do this but not sure how it would be done. 

> By the way, I really like your recent additions to recaf.

:smiley: Its not just me, take a look over at the recently merged PR's

**Comment by shadoxxhd** [comment] 2019-05-07 04:42
>>List sorting according to local relevance and personal usage would add a bit more conveniance, but might take more work to implement than it is worth.

>I'd love to do this but not sure how it would be done.

Prioritizing type names already used inside a given method/class and otherwise sorting by some function of personal usage frequency and frequency in contextual proximity (how often it is mentioned in the current method/class/project) should be pretty good already.
This could be optimized my ML solutions or online type frequency lookups, but due to diminishing returns this optimization would probably be unneccessary/not worth the time spent implementing it.

**Comment by Col-E** [comment] 2019-05-08 04:34
![assembler](https://user-images.githubusercontent.com/21371686/57349635-e0767180-7128-11e9-8d50-9435f493e320.png)

Error handling essentially done :ok_hand: 

Faulty lines have the :stop_sign: and hovering over them shows the error message.

**Comment by Col-E** [comment] 2019-05-10 12:55
![2019-05-10_08-53-55](https://user-images.githubusercontent.com/21371686/57528782-3998fd80-7301-11e9-808f-8b11fc4f905a.gif)

Started on tab-completion in 748b814853a74d95a302a53afb278e2db2a425e3

**Comment by Col-E** [comment] 2019-05-11 00:14
In 9bbdc71972384c6a181ae7941be806099f76dcb2 I've refactored the assembler to be separate from the UI. So if you're using Recaf _(which is on JitPack as a dependency)_ once `1.13` is out, you can use the assembler as a library. See [`Assembly.java`](https://github.com/Col-E/Recaf/blob/master/src/me/coley/recaf/parse/assembly/Assembly.java)

**Comment by Col-E** [comment] 2019-05-12 09:37
Variable opcodes can now use names instead of numeric indices.But if you use numbers, they will use those given values. 

**Special case**:  `this` and `ALOAD 0` will map to the same thing.

![image](https://user-images.githubusercontent.com/21371686/57580474-075ddc00-7478-11e9-8ce0-f77a953dd15b.png)

**Comment by Col-E** [comment] 2019-05-15 07:28
Autocomplete for field and method instructions :+1: 

![2019-05-15_03-26-16](https://user-images.githubusercontent.com/21371686/57756476-55b1eb80-76c1-11e9-93f3-eca5e064f498.gif)

**Comment by Jugen** [comment] 2019-05-21 06:17
The annoying issue in RichTextFx referenced 11 days ago above (10 May) has been fixed in [RichTextFx  0.10.1](https://github.com/FXMisc/RichTextFX/releases/tag/v0.10.1)
The odd page up and down behavior has also been changed to what is usually expected.

**Comment by Col-E** [comment] 2019-05-23 13:42
Pushed a release, 1.13.0, that lets you play with the assembler :hammer_and_wrench:

**Comment by Col-E** [comment] 2019-05-30 10:05
FxAssembler can now be used in the instruction list window as of a71cb54d88bd5d9629a43f99326bd8d55c1a6d3f

**Comment by Col-E** [comment] 2019-06-29 00:51
Closing this as the primary suggestions have been implemented. The following are my opinions on the _"minor"_ suggestions have not been touched on:

********

> * Add window that lists (other) open windows.

Windows should be displayed in any window-manager software _(Including windows' explorer)_

> * Allow multicursor selection for editing instrutions

Unsure how to implement as follow-up discussion clarified.

> * Add regex search/replace with functional conditions (ie. class name that starts with "wi", data type name "int" (useful eg. if you don't want to want to change the class name Mint to Mlong, but all ints to longs)

**This should be made into it's own issue**. There's a lot I want to do regarding refactoring the search api. The goal would to allow the UI presentation of the Search API to be simplistic like it is now, but also to allow much more complex searches and other actions

* Merging multiple searches together
    * Option for aggregation mode of results (OR, AND, XOR)
* Running simple actions on the results

> * Structure Detection: Allow semiautomatic application of simple structure rules (automate repetetive tasks; eg. if you want to add several class entries to an array, the constructor code for them could be automatically generated when C&P duplicating the last 3 entries (should be optional/configurable)

Again, **this should be it's own issue**. I like this idea but it's very complex and I'm not sure right now how I want to approach this.

> * Allow using tabs instead of new windows?

The tabs are for classes, I personally think including non-class tabs would be confusing and clutter the tab menu much more. Windows can be quickly tabbed between using any window manger software too, so access is easier this way IMO.

**Closed by Col-E** 2019-06-29 00:51 UTC
Labels: enhancement

**Comment by shadoxxhd** [comment] 2019-06-29 00:59
The tabs could be in a appropriately themed windows (main window for classes, another window for currently open methods, another for instruction editor, etc.) or in class windows (all method overview/instruction edit frames are tabs in a class-specific window). The problem with window manager software is that the more windows you have open, the worse navigating them gets (at least in those window managers I've experienced - is there one that can easily structurize hundreds of windows for true O(log(n)) human window search time?).

**Comment by Col-E** [comment] 2019-06-29 01:30
> is there one that can easily structurize hundreds of windows ...

I think at that point you have another problem, why would you have 100+ windows open? I can't recall the last time I had more than 10 open.

**Comment by shadoxxhd** [comment] 2019-06-29 01:45
I never had 100 recaf windows open at the same time, but 15-20 is not too unusual (when extending/tweaking big minecraft mods). Add to that 30+ other windows, and you'll have trouble using alt+tab very effectively.

**Comment by Col-E** [comment] 2019-06-29 03:50
How about this, windows of the same kind being tabbed together (drag two windows near each other to merge).

Method editor windows can be merged together, but they couldn't merge with a instructions list window for instance. 

How's that for a plan?
