### ISSUE TITLE
Crash on macos

### ISSUE THREAD

**Issue by CorruptionHades** [Col-E/Recaf#822] opened 2024-07-11 22:18 UTC
**Describe the bug**

> When trying to launch recaf on macos it crashes

**To Reproduce**

1. Open Terminal
2. Do java --version
3. Check that it matches
```
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8-16)
OpenJDK 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
```
4. Do java -jar recaf.jar

**Exception**
```
00:15:27.411 [main] INFO : Recaf-2.21.14
00:15:27.413 [main] INFO : - Java: 22.0.1 (OpenJDK 64-Bit Server VM)
00:15:27.503 [main] TRACE: Loading configuration
Jul 12, 2024 12:15:28 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @56ed9f5e'
2024-07-12 00:15:29.211 java[2456:95738] *** Assertion failure in -[_NSTrackingAreaAKViewHelper removeTrackingRect:], _NSTrackingAreaAKManager.m:1637
2024-07-12 00:15:29.213 java[2456:95738] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '0x0 is an invalid NSTrackingRectTag. Common possible reasons for this are: 1. already removed this trackingRectTag, 2. Truncated the NSTrackingRectTag to 32bit at some point.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff814a6812a __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81458e0b7 objc_exception_throw + 48
	2   Foundation                          0x00007ff81593ecd8 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x00007ff81813cfe3 -[_NSTrackingAreaAKViewHelper removeTrackingRect:] + 190
	4   libglass.dylib                      0x00000001099a53b9 -[GlassViewDelegate setFrameSize:] + 361
	5   libglass.dylib                      0x00000001099aac88 -[GlassView3D setFrameSize:] + 88
	6   AppKit                              0x00007ff817acc091 -[NSView setFrame:] + 347
	7   libglass.dylib                      0x00000001099aace5 -[GlassView3D setFrame:] + 69
	8   AppKit                              0x00007ff817adcec8 -[NSView resizeWithOldSuperviewSize:] + 694
	9   AppKit                              0x00007ff817adc7fb -[NSView resizeSubviewsWithOldSize:] + 499
	10  AppKit                              0x00007ff817abbf26 -[NSView setFrameSize:] + 1460
	11  AppKit                              0x00007ff817acc091 -[NSView setFrame:] + 347
	12  AppKit                              0x00007ff817adcec8 -[NSView resizeWithOldSuperviewSize:] + 694
	13  AppKit                              0x00007ff817adc7fb -[NSView resizeSubviewsWithOldSize:] + 499
	14  AppKit                              0x00007ff817abbf26 -[NSView setFrameSize:] + 1460
	15  AppKit                              0x00007ff817adac03 -[NSThemeFrame setFrameSize:] + 464
	16  AppKit                              0x00007ff817ada30f -[NSWindow _oldPlaceWindow:fromServer:] + 831
	17  AppKit                              0x00007ff817ad8da2 -[NSWindow _setFrameCommon:display:fromServer:] + 3089
	18  libglass.dylib                      0x000000010999c8ef -[GlassWindow(Java) _setFlipFrame:display:animate:] + 239
	19  libglass.dylib                      0x000000010999c35c -[GlassWindow(Java) _setWindowFrameWithRect:withDisplay:withAnimate:] + 268
	20  libglass.dylib                      0x000000010999c5c9 -[GlassWindow(Java) _setBounds:y:xSet:ySet:w:h:cw:ch:] + 601
	21  libglass.dylib                      0x00000001099b622e Java_com_sun_glass_ui_mac_MacWindow__1setBounds2 + 446
	22  ???                                 0x000000011a8fab3c 0x0 + 4740590396
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by xxDark** [comment] 2024-07-11 22:28
Duplicate of #794 any some others.

**Closed by xxDark** 2024-07-11 22:28 UTC
