### ISSUE TITLE
MacOS: Recaf auto quits when I open it without error

### ISSUE THREAD

**Issue by LoYungSum** [Col-E/Recaf#301] opened 2020-10-23 09:51 UTC
Here is a demo demonstrating it just quits when I try to open it: https://youtu.be/BG3DuG7okD4
And here's the console output just in case someone needs it
```
sunnylo@SunnyLos-MacBook-Air Downloads % java8
sunnylo@SunnyLos-MacBook-Air Downloads % java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
sunnylo@SunnyLos-MacBook-Air Downloads % java -jar /Users/sunnylo/Downloads/recaf-2.11.0-J8-jar-with-dependencies.jar
17:46:47.167 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
Exception in thread "main" java.lang.AssertionError: Failed to get latest supported JFX version
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLatestSupportedJfxVersion(SelfDependencyPatcher.java:221)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLatestDependencies(SelfDependencyPatcher.java:228)
	at me.coley.recaf.util.self.SelfDependencyPatcher.hasCachedDependencies(SelfDependencyPatcher.java:185)
	at me.coley.recaf.util.self.SelfDependencyPatcher.patch(SelfDependencyPatcher.java:73)
	at me.coley.recaf.Recaf.init(Recaf.java:81)
	at me.coley.recaf.Recaf.main(Recaf.java:49)
sunnylo@SunnyLos-MacBook-Air Downloads % java11
sunnylo@SunnyLos-MacBook-Air Downloads % java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
sunnylo@SunnyLos-MacBook-Air Downloads % java -jar /Users/sunnylo/Downloads/recaf-2.11.0-J8-jar-with-dependencies.jar 
17:47:06.576 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
17:47:06.579 [main] INFO :  - Local cache found!
17:47:06.580 [main] INFO :  - Loading dependencies...
17:47:06.614 [main] INFO :  - Done!
17:47:06.615 [main] INFO : Recaf-2.11.0
17:47:07.404 [main] TRACE: Loading configuration
```

**Comment by tomtastic** [comment] 2020-10-23 10:14
Possibly related to https://github.com/Col-E/Recaf/issues/296

**Comment by LoYungSum** [comment] 2020-10-23 10:23
Yep. After creating the file with the `"backend.firsttime": false`, it works

**Comment by Col-E** [comment] 2020-10-24 03:23
Since I'm seeing this consistently on macs only, I may just add an exception for mac users until this can be resolved... I don't have the hardware to test, and when trying to test with others the results are really weird. No uncaught exceptions where it would be reasonable to check, exit code is 0, just nothin.

**Comment by Col-E** [comment] 2020-10-24 17:10
Closing as a duplicate of #296 and I also believe a fix will be coming soon.

**Closed by Col-E** 2020-10-24 17:10 UTC
Labels: Help wanted, bug
