### ISSUE TITLE
I have a bold idea

### ISSUE THREAD

**Issue by xtherk** [Col-E/Recaf#432] opened 2021-12-08 06:35 UTC
Recently I want a java debugger without source code. I know JDB but it's not convenient to use. 
Although the remote debugging of `IntelliJ IDEA` is very convenient, it is not enough to face the confused class, so I continued to search and I found a plug-in based on eclipse, it can be debugged in the bytecode view, I think it’s cool, this is what I want.
If recaf can be realized, it’s really great !

Links:
[Eclipse Marketplace Bytecode-Visualizer](https://marketplace.eclipse.org/content/bytecode-visualizer)
[Home Page](http://drgarbagetools.sourceforge.net/)

**Comment by Col-E** [comment] 2021-12-09 09:51
Duplicate of #153 - Already been planned for a while :)

Additionally the linked tool by Dr Garbage unfortunately depends heavily on the Eclipse API. Take a look at their `JDIStackFrameSourceDisplayAdapter` for an example. So I can't really look at it as an example.

**Closed by Col-E** 2021-12-09 09:51 UTC
Labels: duplicate/existing, enhancement
