### ISSUE TITLE
`multianewarray [L 1` silently fails 

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#843] opened 2024-08-06 11:53 UTC
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

1. Add a class `L`
2. Add the following bytecode
3. Save the bytecode
4. The save will appear to succeed, but there will be an exception on the commandline and the class will be unchanged

```
.method static test ()V {
	code: {

		iconst_0		
		multianewarray [L 1
		pop
	}
}
```
(yes, I am aware, that compilation should fail. It should however not fail silently)

**Exception**

If applicable, add the exception/stacktrace.
```
13:52:15.581 [AssemblerPane/ForkJoinPool.commonPool-worker-25] ERROR: Uncaught exception when assembling contents of JVM class: L
java.lang.IllegalStateException: Expected InstanceType
	at dev.xdark.blw.type.TypeReader.read(TypeReader.java:42)
	at dev.xdark.blw.type.TypeReader.read(TypeReader.java:25)
	at dev.xdark.blw.type.Types.arrayTypeFromDescriptor(Types.java:80)
	at me.darknet.assembler.compile.visitor.BlwCodeVisitor.visitMultiANewArrayInsn(BlwCodeVisitor.java:359)
	at me.darknet.assembler.instructions.jvm.JvmInstructions.lambda$registerInstructions$7(JvmInstructions.java:95)
	at me.darknet.assembler.instructions.Instruction.transform(Instruction.java:43)
	at me.darknet.assembler.ast.specific.ASTMethod.accept(ASTMethod.java:79)
	at me.darknet.assembler.ast.specific.ASTClass.accept(ASTClass.java:172)
	at me.darknet.assembler.transformer.Transformer.transform(Transformer.java:43)
	at me.darknet.assembler.compile.JvmCompiler.compile(JvmCompiler.java:91)
	at software.coley.recaf.services.assembler.AbstractAssemblerPipeline.compile(AbstractAssemblerPipeline.java:120)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline.assemble(JvmAssemblerPipeline.java:73)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline$Proxy$_$$_WeldClientProxy.assemble(Unknown Source)
	at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lambda$assemble$31(AssemblerPane.java:405)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by therathatter** [comment] 2024-08-06 20:34
Dude. Just open one issue next time.

**Comment by C0D3-M4513R** [comment] 2024-08-06 20:59
With the way Col-E renamed #837 I thought it was appropriate to open multiple issues.

**Comment by Amejonah1200** [comment] 2024-08-06 21:41
The title was made like so, cuz Matt thought there was only one issue and so wanted to have a more generalized title. You could've just reported more cases and change the title accordingly...

**Comment by Col-E** [comment] 2024-08-06 23:36
> Dude. Just open one issue next time.

There are cases where bulk items can be put into one but more often than not people put _too much_ into one issue so I prefer them keep items separate.

**Comment by Col-E** [comment] 2024-08-14 04:16
Duplicate of #842

**Closed by Col-E** 2024-08-14 04:16 UTC
Labels: duplicate/existing, enhancement, 4.X
