### ISSUE TITLE
Illegal named methods or variable names

### ISSUE THREAD

**Issue by MizzMaster** [Col-E/Recaf#274] opened 2020-09-12 10:39 UTC
You know that there are words that we cant use while declaring a method or a variable. BUT FU***NG OBFUSCATORS CAN!
I spent more than 30 hours dealing with bugs. I got mad, sorry.

If an obfuscator rename a variable with an illegal(unicode or reserved keywords), this causes Recaf suck while parsing decompiled code. If an variable name gets invisible, that means it is unicode, but if a method name gets unparseable, it means you cant even change it's name using table mode.

In my jar, there are 2 methods named "do" and "if" and maybe a lot more. I don't know if it is your job to fix this but it causes your program to cant even rename this illegal method. If you say that is not my job, i will open an issue on "Java Deobfuscator" repo.

Btw, you can run CFR with -renameillegalidents to prevent unicode bug.

**Comment by andylizi** [comment] 2020-09-12 13:06
`1.x` versions of Recaf allowed changing all CFR options. It'd be nice if this can be supported again. Some reflection (e.g. [on here](https://github.com/leibnitz27/cfr/blob/00f0a883e8e3423a0e3d24930a37560bfbfbdf34/src/org/benf/cfr/reader/util/getopt/OptionsImpl.java#L266-L539)) can be used to avoid the tedious work of keeping all the options up-to-date.

`--renameillegalidents` would solve the problem in this case.

**Comment by MizzMaster** [comment] 2020-09-12 13:37
Does --renameillegalidents change the ones that use reserved keywords?

**Comment by andylizi** [comment] 2020-09-12 13:38
`$ cfr --help renameillegalidents`
> Rename identifiers which are **not valid java identifiers**.  Note - this WILL break reflection based access, so is not automatically enabled.

Yes.

**Comment by MizzMaster** [comment] 2020-09-12 13:40
I hope this does not break Recaf

**Comment by MizzMaster** [comment] 2020-09-12 13:42
CFR just decompiles and gives us text based .class file. Not all the time perfect and not all the time same, i was trying to rename that illegal metod in Recaf but i couldnt

So, CFR doesnt change the actual name, it just changes while showing you up

**Comment by MizzMaster** [comment] 2020-09-12 13:47
And i forgot to mention, I was trying to rename it on "Table Mode", but when i press enter, it does nothing

**Comment by andylizi** [comment] 2020-09-12 13:52
~If you just want to rename stuff, the Table view will surely work?~

Or not, I guess.

---

By the way, I've always find the decompile view not very helpful because any obfuscation can easily break the parser, and if that failed, the whole page is reduced to a fancy textbox. Proper IDEs and language servers have the ability to parse partial source, but I imagine that'd be hard to implement.

**Comment by Col-E** [comment] 2020-09-12 14:42
Yeah, decompile mode is not intended for obfuscated code. This is stated in the docs: https://www.coley.software/Recaf/doc-edit-mode-decompile.html

I wish it could be better suited but all I can do is implement JavaParser, which is very strict and doesn't allow for small mistakes in the decompiled code. Its understandable why it is that way, but it is unfortunate. 

CFR renaming is cool but would break how decompile mode context actions work.

You should change the default mode to table otherwise. Which shows fields and methods properly. If renaming doesn't work can you provide what is necessary for minimally reproducing the issue?

**Comment by MizzMaster** [comment] 2020-09-12 16:30
I tried to reproduce this issue by writing a new class from scratch, it didn't happen anywhere. But I took the .class file from the jar that I was working on, and loaded it on Recaf, I couldn't rename variables using Table Mode.

If it is possible, can you give me a link that I can send this class file to you? (Maybe it's not suitable for guidelines)

Actually, if this issue coming from JUST because obfuscation, I can open an issue on Java Deobfuscator to fix that by renaming the illegal idents, or maybe there is already a transformer to do that, whatever, this caused Recaf to cant rename.

Before I sent this post, I checked if I can edit the name on assembler, I could. But i dont know if it is renamed in other classes

**Comment by Col-E** [comment] 2020-09-12 17:17
Put it into a zip and drag and drop it in a comment here or dm me on discord

**Comment by MizzMaster** [comment] 2020-09-12 17:46
[IllegalClass.zip](https://github.com/Col-E/Recaf/files/5213055/IllegalClass.zip)

**Comment by Col-E** [comment] 2020-09-17 03:41
Ah the renaming failure is because they put junk data into the signature attribute and ASM crashes.

**Comment by Col-E** [comment] 2020-09-17 04:02
`2.8.0` should allow you to rename these things :)

It may still have some trouble with whitespace.... that's a tougher problem.

**Comment by Col-E** [comment] 2020-09-23 05:01
Closing as the specific problem has been resolved.

As mentioned, whitespace names and other tricky things are on a different level.

**Closed by Col-E** 2020-09-23 05:01 UTC
Labels: bug
