### ISSUE TITLE
AgentLoadException: 0

### ISSUE THREAD

**Issue by Demono5060** [Col-E/Recaf#528] opened 2022-04-27 07:57 UTC
**Describe the bug**

> Recaf failed to connect to the target VM: 9208

**Exception**

```
com.sun.tools.attach.AgentLoadException: 0
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:109)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:120)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:148)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
	at me.coley.recaf.ui.controls.pane.AttachPane$VMInfo.lambda$attach$5(AttachPane.java:417)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Col-E** [comment] 2022-04-27 13:03
Need more information to do anything. 

The agent exceptions should have a `caused by` section. 

What were you trying to attach to?

**Comment by Col-E** [comment] 2024-05-19 21:39
Closing as 4.X is the only branch we're working on going forward. Agent attach has been tweaked significantly since this issue on the new branch.

**Closed by Col-E** 2024-05-19 21:39 UTC
Labels: usage, Missing details
