### ISSUE TITLE
Assembler's assumption that INVOKEVIRTUAL sets isInterface=false has edge cases

### ISSUE THREAD

**Issue by KTibow** [Col-E/Recaf#454] opened 2022-01-24 14:36 UTC
**Describe the bug**

> I was trying to patch a jar with a bug in it, and when I changed the de-assembled bytecode a bit then changed it back to the original, the output didn't work.

(FYI I don't usually do Java, so I basically know nothing, and I'm probably missing something obvious. This probably isn't even your problem, but I don't know what else could be.)
**To Reproduce**

1. Open sample [nocomcrash-1.0.0.zip](https://github.com/Col-E/Recaf/files/7926231/nocomcrash-1.0.0.zip)
2. Navigate to ChatScreenMixin
3. Go to table view, and edit `atomic_interceptChatMessage` with the assembler.
4. Add any line of code, save, remove it, and save.
5. Output bytecode is different than the original, and when you try to use its main functionality (type "=nccrash" into chat on Paper Minecraft 1.18), it crashes.

**Exception**

If applicable, add the exception/stacktrace.
```
[19:39:18] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: keyPressed event handler
	at net.minecraft.class_437.method_25412(class_437.java:496) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:380) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:472) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:472) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Method 'net.minecraft.class_2561 net.minecraft.class_2561.method_30163(java.lang.String)' must be InterfaceMethodref constant
	at net.minecraft.class_408.redirect$bjo000$atomic_interceptChatMessage(class_408.java:1033) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25404(class_408.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:384) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
	... 27 more
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/23/22, 7:39 PM
Description: keyPressed event handler

java.lang.IncompatibleClassChangeError: Method 'net.minecraft.class_2561 net.minecraft.class_2561.method_30163(java.lang.String)' must be InterfaceMethodref constant
	at net.minecraft.class_408.redirect$bjo000$atomic_interceptChatMessage(class_408.java:1033)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:384)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1466(class_309.java:380)
	at net.minecraft.class_309.method_22678(class_309.java:472)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_309.method_22676(class_309.java:472)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_408.redirect$bjo000$atomic_interceptChatMessage(class_408.java:1033)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:384)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1466(class_309.java:380)
	at net.minecraft.class_309.method_22678(class_309.java:472)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_309.method_22676(class_309.java:472)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1466(class_309.java:380)
	at net.minecraft.class_309.method_22678(class_309.java:472)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_309.method_22676(class_309.java:472)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['KTibow'/256, l='ClientLevel', x=250.96, y=68.44, z=58.75]]
	Chunk stats: 1024, 450
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,80,-64), Section: (at 0,0,0 in 2,5,-4; chunk contains blocks 32,-64,-64 to 47,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 83777 game time, 83777 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Screenshots**

**Comment by KTibow** [comment] 2022-01-24 14:47
Wait, so is this a problem with Recaf or one of its dependencies, or is there something I forgot? Given that it's a Minecraft mod, dependencies are a bit weird (no single jar file from what I understand).

**Comment by xxDark** [comment] 2022-01-24 14:49
> Wait, so is this a problem with Recaf or one of its dependencies, or is there something I forgot? Given that it's a Minecraft mod, dependencies are a bit weird (no single jar file from what I understand).

I updated my first comment, including all dependencies probably wont help in this case, and I'm aware of an easy fix for this one, because it will require changes to AST parser. I'll suggest to wait for Matt's response.
Right now what you can do is disable JVM's verifier (-noverify flag).

**Comment by Col-E** [comment] 2022-01-24 14:54
> JVM expects interface method call, while ASM produced virtual call. Can you add all dependencies required to check if that solves the problem?

At work atm, but is the problem:

- dissassembler emitting `INVOKEVIRTUAL` and `INVOKEINTERFACE` incorrectly
- assembler writing `INVOKEVIRTUAL` and `INVOKEINTERFACE` incorrectly
- ASM somehow messing up after assembler builds model for what instructions should be used

?

I can check myself more in depth later.

**Comment by xxDark** [comment] 2022-01-24 14:57
> At work atm, but is the problem:

The problem is that JVM for whatever reason has two ways to store method references (we just discussed that in Discord, lol), and whenever you call a method, it will:
Set `isInterface` flag to true, if you are calling method on an interface.
Set `isInterface` flag to false, if you are calling method on a non-interface class.
Recaf loses that information, and leaves the job of determining the correct CP entry to ASM, and it fails doing so.
See `MethodInsnNode#itf` field

**Comment by Col-E** [comment] 2022-01-24 14:59
Right, if the op is virtual, we assume itf=false. If the op is interface we assume itf=true.
Is the op virtual, but the target should be itf=true then?

**Comment by xxDark** [comment] 2022-01-24 15:00
> Right, if the op is virtual, we assume itf=false. If the op is interface we assume itf=true. Is the op virtual, but the target should be itf=true then?

That's what ASM does, but it may be incorrect in some cases:
```Java
    this(opcode, owner, name, descriptor, opcode == Opcodes.INVOKEINTERFACE);
```

**Comment by Col-E** [comment] 2022-01-24 15:09
Ugh, then we'll have to actually check the target being invoked for EVERY instruction.... Or add the flag to the output/input parser.... 

I hate both of these options 😭

**Comment by xxDark** [comment] 2022-01-24 15:11
> Ugh, then we'll have to actually check the target being invoked for EVERY instruction.... Or add the flag to the output/input parser....
> 
> I hate both of these options 😭

Another way is to add this flag to the end of the `MethodInsnAST`, but this will require changes to all tests because they probably expect an output without the flag.

**Comment by Col-E** [comment] 2022-01-24 15:11
Right, which is annoying as hell...

**Comment by KTibow** [comment] 2022-01-24 23:04
Is there anything I can do in the meantime? `-noverify` is having no effect.

**Comment by xxDark** [comment] 2022-01-24 23:20
What version of JDK are you running on? I suspect that Oracle decided to completely remove `-noverify` flag.

**Comment by KTibow** [comment] 2022-01-24 23:35
`java-17-openjdk-amd64`. I also tried `-Xverify:none`, but that didn't work, either.

**Comment by xxDark** [comment] 2022-01-25 10:28
> `java-17-openjdk-amd64`. I also tried `-Xverify:none`, but that didn't work, either.

You may try downgrading to JDK 16, not sure if it will run though.

**Comment by Storyyeller** [comment] 2022-06-02 21:09
IIRC, Java 8 added the ability to invoke interface methods via invokevirtual (or maybe it was the other way around), so you can no longer infer the constant type just from the instruction. That's why I changed the Krakatau assembler to require you to specify it explicitly, back in 2015.

**Comment by Col-E** [comment] 2024-05-19 21:49
In 4.x we have introduced opcode aliases to support this.

- invokevirtualinterface
- invokespecialinterface
- invokestaticinterface

**Closed by Col-E** 2024-05-19 21:49 UTC
Labels: bug
