### ISSUE TITLE
decompilation

### ISSUE THREAD

**Issue by LovesAsuna** [Col-E/Recaf#128] opened 2019-06-11 08:56 UTC
**Describe the bug**
In fact, the decompilation of recaf is inconsistent with the decompilation of jdgui, which leads to the inability to recompile directly.
> A clear and concise description of what the bug is.

**To Reproduce**
1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Screenshots**

**Comment by andylizi** [comment] 2019-06-11 11:16
It seems you're Chinese so I'll use Chinese directly to save time and effort:

我不明白你在说什么。如果我没理解错的话，你想表达的是 ”Recaf 中的反编译结果与 jd-gui 的不一致，因此没法直接重编译反编译后的源码“。这句表述中存在三个问题：

1. 重编译反编译后的源码跟 jd-gui 有什么关系？没看出来前半句话跟后半句话有任何的因果关系呀。
2. “反编译”这件事，跟翻译一样，本来就不是100%准确的。完全精确的反编译在理论上就是不可能的事情（虽然可以很接近就是了）。反编译后的结果不能直接编译是完全不意外的。因为一段字节码可以对应无数段等效的源码，因此两种反编译器的输出结果会不同也是完全不意外的。这跟机器翻译其实是差不多的道理。百度翻译和 Google 翻译的结果不一样你会觉得奇怪吗？
3. Recaf 里的反编译功能是直接调用的 CFR，因此即使反编译器真的有问题，也（多半）不会是 Recaf 的问题。

以及 jd-gui 算是一个写的很烂的、早已不再维护的古董反编译器了。它生成的代码里面问题一堆一堆的。而且还不支持 Java 8。它跟其他反编译器比唯一的优势就是它有图形界面，而且使用起来很方便。因此如果你的目的是把代码直接拿给编译器编译，而不是给人阅读的话，完全不建议使用 jd-gui。

---

A non-verbatim translation/summary for those who don't understand Chinese: 
1. I don't see any logical connection between the first part of the sentence ("the decompilation of recaf is inconsistent with the decompilation of jdgui") and the second part ("unable to directly recompile").
2. Decompilation isn't guaranteed to be 100% precise. In fact, it is completely to be expected that directly compile the result of a decompiler without any modification will fail. In the same way, is also completely to be expected that two decompiler's result will differ. A lot like machine translation actually.
3. The decompilation feature in Recaf is "powered by" CFR. So any bug report that involves decompiling inaccuracies should go to the maintainer of CFR.
4. JD-GUI (or more specifically, JD-CORE) is an ancient, long since unmaintained and generally not-very-good decompiler (its UI is another different matter). I won't recommend it for any purpose besides a quick, rough overview anyway.

**Comment by Col-E** [comment] 2019-06-11 11:20
Andy summarized it well. Recaf does not use JD-GUI/JD-Core. I don't plan on adding it for the 4th reason.

**Comment by LovesAsuna** [comment] 2019-06-12 03:12
既然是梨子大大..我主要就是想重编译spigot的一些文本，无奈重编译会失败

**Comment by Col-E** [comment] 2019-06-12 11:19
When you attempt to recompile code any failures are shown in the console. Can you share your sample and what you wish to change?

**Comment by andylizi** [comment] 2019-06-12 11:36
What the author of this issue said: basically "I want to change some texts in some program but recompilation fails."

唔，关于重编译失败的问题的话你需要给出日志、描述和例子（失败时输出了什么，你改了什么，你改的是什么东西）。但其实如果你只是想改文本的话，建议使用以下几种方法：
1. 既然重新编译反编译后的结果会失败的话，那就不编译，直接修改字节码呗。本来改字节码是个挺有技术含量的活，但既然你只是想改字符串字面量，那就简单的多：
    1. 用 Recaf 打开你要改的 jar，定位到你要改的那段文本所在的类以及方法。
    2. 打开该方法的指令编辑窗口或 assembler 窗口，在里面找到 `LDC + "你要改的字符串"` 这条指令。比如说我们想改 Spigot 服务器启动后出现的 "Loading libraries, please wait..." 信息：
![recaf-1](https://user-images.githubusercontent.com/12008103/59343903-6ba5e100-8d3f-11e9-8286-d1704857b902.png)
    图中两个窗口都可以。看你喜欢哪个。如果你用指令编辑的话就右击那条 `LDC` 指令，点编辑，然后在弹出的输入框里将字符串改为你想要的样子。如果你用 Assembler 的话就……编辑，就好了。然后保存。这是最快捷的方法。
2. 不想/不会改字节码的话，那你就只能自己编译了。因为 Spigot 是开源的……所以你干嘛要反编译来着的？
不过虽然说开源是开源，但考虑到 Spigot 那个极其复杂的项目结构，要自己修改+编译也不是简单的活。如果你之前没自己编译过服务端的话，你需要使用 BuildTools。Spigot 官网有个 [写的很清晰的教程](https://www.spigotmc.org/wiki/buildtools/)，或者实在不行你也可以去 mcbbs 查。总之先用 BuildTools 构建出一份未修改过的服务端，然后你就可以在……呃……这里面涉及到了代码的部分太多了，我不知道你具体想改的东西是属于哪个组件的话，没法告诉具体在哪个特定的文件夹里。太麻烦也不（lǎn）好（dé）在这一步步的写指南。只能建议你自己摸索了。我还是以我之前那个 "Loading libraries, please wait..." 作例子，它在 `BuildTools根目录\Spigot\CraftBukkit\src\main\java\org\bukkit\craftbukkit\Main.java` 里面：
![2](https://user-images.githubusercontent.com/12008103/59344585-fc30f100-8d40-11e9-8abb-19eea6882479.png)
修改完后怎么编译也是个问题，取决于你修改的是哪个组件……关于怎么做的信息能在 BuildTools 的 `org.spigotmc.builder.Builder` 类里找到，但你看不看得懂又是另一回事了。但这个因为真的复杂，我也没法在这都写出来。
所以说了这么多还是建议你用第一种方法。
3. 用反编译或第二步所说的方式获取到源码，然后单独编译需要修改的那个类，然后把编译好的类替换到原来的 jar 里。这也是一种方法。

---

What I said: Recompilation failure? Need more info. Logs, step-to-reproduces and/or samples.
However, if you just wanted to change some string literal, you can:
1. Open the method that contains the strings you want to change. `Edit instructions` or `Edit with assembler`. Locale `LDC + "the string you want"`. Edit it. Save it. Done.
2. Or you can compile yourself. Spigot is [OPEN-SOURCED](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/). Why bother decompiling.
But is not that easy. Spigot has a very complicated project structure. Designed partly to avoiding DMCA, partly because... it's just that complicated. That's why they developed [BuildTools](https://www.spigotmc.org/wiki/buildtools/) solely for the purpose of building Spigot. And it automatically reverts any changes you made when building. And because its multi-moduled project structure I can't tell you where the files you want is located because I don't know the change you want is in which part of the Spigot. And... I'm going to stop translating now. It's just _complicated_. Ugh.
So I suggest using the first method.
3. Use the method 2 or a decent decompiler to get the source. Then compile, and only compile that specified class in which contains your desired changes. Then replace the class file in the jar using a file archiver or something.

**Comment by LovesAsuna** [comment] 2019-06-12 11:40
我一直都是buildtool的呀，只是因为反编译之后看起来更直观不用一个一个去查了。然后又因为recaf貌似是不支持换行的(捂脸)

**Comment by andylizi** [comment] 2019-06-12 11:45
What he said: "I used BuildTools, but the decompiler is more \"direct\", without the need to determine what module it belongs. And because Recaf doesn't seem to support line feed."

> 看起来更直观不用一个一个去查了

有道理。

> 然后又因为recaf貌似是不支持换行的

什么……换行？你说的是哪里的换行？没有明白。

---

What I said: You have a point about more direct. What do you mean by "line feed"?

**Comment by Col-E** [comment] 2019-06-12 11:59
I'm going to re-open this as it seems I may have just misunderstood what the issue was about.

Also, I pushed a commit that changes the default CFR options. It looks like the values I had before may have disabled some of the sugar effects _(Which would make switch statements and a few other things decompile in an ugly way which is not compiler-satisfactory)_

**Comment by Col-E** [comment] 2019-07-04 21:20
Closing again. If you can describe what `line feed` means, I'll re-open this issue if its something relevant to add.

**Closed by Col-E** 2019-07-04 21:20 UTC

**Comment by andylizi** [comment] 2019-07-05 07:23
I think he means #130 (title translates to "LDC doesn't support \n").

**Comment by LovesAsuna** [comment] 2019-07-05 07:25
Yes,you have already fixed the problem

**Comment by Col-E** [comment] 2019-07-05 11:02
Oh, good to know :grin:
