### ISSUE TITLE
Restore cursor after rename

### ISSUE THREAD

**Issue by u9g** [Col-E/Recaf#455] opened 2022-01-25 05:30 UTC
## restore cursor after rename

would be nice to keep working after a rename in the same spot

**Comment by Col-E** [comment] 2022-01-25 05:58
The problem is how it works makes it rather difficult to accurately determine where the cursor was.

When you rename a class or method, all the references to it get updated. The classes that have changes made in them are re-decompiled and the UI refreshes. This resets the cursor, but we can sort of work around that. But its limited. We know roughly how far down the text the cursor was and can estimate where it was. That or we can use the exact line info. But neither will get you exactly where you were before.

I'd like to do this, but I'm not sure if its super feasible right now with how we implement things. The reason IntelliJ and other IDE's can do this is since they operate in terms of an AST. Updating the model can update the text of the editor and reset the cursor to the beginning of the element in the AST where it was before. Recaf has no such persistent AST system.

**Comment by Col-E** [comment] 2022-05-23 04:31
Closing since atm this isn't really possible. The best we can do is estimate the scroll/caret position, which we do in 3X.

**Closed by Col-E** 2022-05-23 04:31 UTC
Labels: enhancement
